development: &defaults
  adapter: mysql2
  encoding: utf8
  database: peatio_production
  username: root
  password: 111111
  pool: 10
  reconnect: true
  host: mysql

test:
  <<: *defaults
  database: peatio_test

production:
  <<: *defaults
  database: peatio_production
